x-logging: &loki-logging
  driver: loki
  options:
    loki-url: "http://172.17.0.1:4100/loki/api/v1/push"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
      while ! nc -z db 3306; do
        echo 'waiting for mysql...'
        sleep 1
      done;
      echo 'mysql is ready';
      cd /var/www/html &&
      composer install &&
      php artisan key:generate &&
      php artisan migrate --seed &&
      php artisan serve --host=0.0.0.0 --port=80
      "
    ports:
      - "8081:80"
    environment:
      APP_DEBUG: "true"
      APP_ENV: "dev"
      APP_KEY: "base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4="
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: app_database
      DB_USERNAME: app_user
      DB_PASSWORD: app_password
    logging: *loki-logging
    depends_on:
      - db
      - loki

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: app_root_password
    volumes:
      - db_data:/var/lib/mysql

  loki:
    image: grafana/loki
    container_name: monitoring-loki
    ports:
      - "4100:3100"
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml
      - loki:/data/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail
    container_name: pns-promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./monitoring/promtail-config.yaml:/etc/promtail/config.yml
    network_mode: host
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana
    container_name: pns-grafana
    ports:
      - "4000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=giresfanou@gmail.com
      - GF_SMTP_PASSWORD=lnye vxvs zluq ihya

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  nodeexporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    ports:
      - "9100:9100"

  # cadvisor:
  #   image: google/cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   ports:
  #     - "8082:8080"

volumes:
  db_data:
  grafana-storage:
  loki:
# docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
# sudo systemctl restart docker
