services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
      while ! nc -z db 3306; do
        echo 'waiting for mysql...'
        sleep 1
      done;
      echo 'mysql is ready';
      cd /var/www/html &&
      composer install &&
      php artisan key:generate &&
      php artisan migrate --seed &&
      php artisan serve --host=0.0.0.0 --port=80
      "
    ports:
      - "8081:80"
    environment:
      APP_DEBUG: "true"
      APP_ENV: "dev"
      APP_KEY: "base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4="
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: app_database
      DB_USERNAME: app_user
      DB_PASSWORD: app_password
    logging: *loki-logging
    depends_on:
      - db
      - loki

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: app_root_password
    volumes:
      - db_data:/var/lib/mysql
