global:
  scrape_interval: "1m"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

scrape_configs:
  - job_name: "nodeexporter"
    static_configs:
      - targets: ["nodeexporter:9100"]
  # - job_name: 'app'
  #   static_configs:
  #     - targets: ['app:80']
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
