name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: List all container
        run: docker ps

      - name: Run docker compose
        run: docker compose up -d

      - name: List all container
        run: docker ps

      - name: Build and push Docker image with Buildx
        run: docker buildx build --push -t th3f0r31gn3r/sample-app:latest .
