name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Wait for services to start
        run: |
          docker exec app bash -c "while ! nc -z db 3306; do sleep 1; done"
          sleep 60

      - name: Run laravel test
        run: php artisan test

      - name: Build and push Docker image
        run: |
          docker build -t th3f0r31gn3r/sample-app:latest .
          docker push th3f0r31gn3r/sample-app:latest
